[tasks.format]
description = "Format code"

run = "cargo fmt"


[tasks.lint]
description = "Lint code"

run = "cargo clippy -- -D warnings"


[tasks.test]
description = "Run tests"

run = "cargo test"


[tasks.build]
description = "Build project"

run = "cargo build --release"


[tasks.audit]
description = "Audit dependencies"

run = "cargo audit"


[tasks.docs:build]
description = "Build documentation"

run = "cargo doc --no-deps --open"

